export const tagOptions = [
  { value: 'abtesting', label: 'abtesting' },
  { value: 'alpha', label: 'alpha' },
  { value: 'analysis', label: 'analysis' },
  { value: 'api', label: 'api' },
  { value: 'application', label: 'application' },
  { value: 'architecture', label: 'architecture' },
  { value: 'backend', label: 'backend' },
  { value: 'beta', label: 'beta' },
  { value: 'blocked', label: 'blocked' },
  { value: 'browser', label: 'browser' },
  { value: 'bug', label: 'bug' },
  { value: 'bugfix', label: 'bugfix' },
  { value: 'cache', label: 'cache' },
  { value: 'cicd', label: 'cicd' },
  { value: 'cloud', label: 'cloud' },
  { value: 'cms', label: 'cms' },
  { value: 'crm', label: 'crm' },
  { value: 'css', label: 'css' },
  { value: 'cta', label: 'cta' },
  { value: 'database', label: 'database' },
  { value: 'deploy', label: 'deploy' },
  { value: 'design', label: 'design' },
  { value: 'devops', label: 'devops' },
  { value: 'domain', label: 'domain' },
  { value: 'feature', label: 'feature' },
  { value: 'feedback', label: 'feedback' },
  { value: 'fix', label: 'fix' },
  { value: 'framework', label: 'framework' },
  { value: 'frontend', label: 'frontend' },
  { value: 'fullstack', label: 'fullstack' },
  { value: 'growth', label: 'growth' },
  { value: 'hotfix', label: 'hotfix' },
  { value: 'html', label: 'html' },
  { value: 'implementation', label: 'implmentation' },
  { value: 'integration', label: 'integration' },
  { value: 'interface', label: 'interface' },
  { value: 'javascript', label: 'javascript' },
  { value: 'loadtest', label: 'loadtest' },
  { value: 'localization', label: 'localization' },
  { value: 'material', label: 'material' },
  { value: 'metric', label: 'metric' },
  { value: 'mobile', label: 'mobile' },
  { value: 'mockup', label: 'mockup' },
  { value: 'monitoring', label: 'monitoring' },
  { value: 'navigation', label: 'navigation' },
  { value: 'optimization', label: 'optimization' },
  { value: 'organization', label: 'organization' },
  { value: 'patch', label: 'patch' },
  { value: 'performance', label: 'performance' },
  { value: 'platform', label: 'platform' },
  { value: 'plugin', label: 'plugin' },
  { value: 'portal', label: 'portal' },
  { value: 'production', label: 'production' },
  { value: 'react', label: 'react' },
  { value: 'refactor', label: 'refactor' },
  { value: 'route', label: 'route' },
  { value: 'seed', label: 'seed' },
  { value: 'seo', label: 'seo' },
  { value: 'server', label: 'server' },
  { value: 'service', label: 'service' },
  { value: 'simulation', label: 'simulation' },
  { value: 'syles', label: 'syles' },
  { value: 'system', label: 'system' },
  { value: 'task', label: 'task' },
  { value: 'testing', label: 'testing' },
  { value: 'ui', label: 'ui' },
  { value: 'unittest', label: 'unittest' },
  { value: 'update', label: 'update' },
  { value: 'user', label: 'user' },
  { value: 'ux', label: 'ux' },
  { value: 'vm', label: 'vm' },
  { value: 'wireframe', label: 'wireframe' },
  { value: 'wish', label: 'wish' },
];

export const progressOptions = [
  {
    value: 'none',
    label: 'None',
  },
  {
    value: 'planned',
    label: 'Planned',
  },
  {
    value: 'inprogress',
    label: 'In Progress',
  },
  {
    value: 'blocked',
    label: 'Blocked',
  },
  {
    value: 'completed',
    label: 'Completed',
  },
];

export const priorityOptions = [
  {
    value: 'none',
    label: 'None',
  },
  {
    value: 'wish',
    label: 'Wish',
  },
  {
    value: 'low',
    label: 'Low',
  },
  {
    value: 'medium',
    label: 'Medium',
  },
  {
    value: 'high',
    label: 'High',
  },
];
